//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAirData.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Environmental_Data_2020Entities : DbContext
    {
        public Environmental_Data_2020Entities()
            : base("name=Environmental_Data_2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aktivitet_Table> Aktivitet_Table { get; set; }
        public virtual DbSet<DataType_Table> DataType_Table { get; set; }
        public virtual DbSet<Enhed_Table> Enhed_Table { get; set; }
        public virtual DbSet<Maalested_Table> Maalested_Table { get; set; }
        public virtual DbSet<Measurement_Table> Measurement_Table { get; set; }
        public virtual DbSet<Opstilling_Table> Opstilling_Table { get; set; }
        public virtual DbSet<Product_Table> Product_Table { get; set; }
    }
}
