//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationAirData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Data
    {
        public Nullable<System.DateTime> time_stamp { get; set; }
        public string Data_Type { get; set; }
        public string Enhed_Name { get; set; }
        public string Stof_Name { get; set; }
        public string MeasurePlace_Name { get; set; }
        public Nullable<double> Measurement_Result { get; set; }
        public string Constuction_Code { get; set; }
        public int AktivitetId { get; set; }
    }
}
