'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Aktivitet_Table
    Public Property AktivitetId As Integer
    Public Property AktivitetTypeId As Nullable(Of Integer)
    Public Property OpstillingId As Nullable(Of Integer)
    Public Property DatoMaerke As Nullable(Of Date)
    Public Property ExpPeriodeTypeId As Nullable(Of Integer)

    Public Overridable Property Product_Table As ICollection(Of Product_Table) = New HashSet(Of Product_Table)

End Class
