'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Environmental_Data_2020Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Environmental_Data_2020Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Aktivitet_Table() As DbSet(Of Aktivitet_Table)
    Public Overridable Property DataType_Table() As DbSet(Of DataType_Table)
    Public Overridable Property Maalested_Table() As DbSet(Of Maalested_Table)
    Public Overridable Property Opstilling_Table() As DbSet(Of Opstilling_Table)
    Public Overridable Property Product_Table() As DbSet(Of Product_Table)
    Public Overridable Property Stof_Table() As DbSet(Of Stof_Table)

End Class
