'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Maalested_Table
    Public Property MaaleStedId As Integer
    Public Property Navn As String
    Public Property Akronym As String
    Public Property GeometriId As Nullable(Of Integer)

    Public Overridable Property Opstilling_Table As ICollection(Of Opstilling_Table) = New HashSet(Of Opstilling_Table)

End Class
