'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product_Table
    Public Property ProduktId As Integer
    Public Property AktivitetId As Nullable(Of Integer)
    Public Property ProduktTypeId As Nullable(Of Integer)

    Public Overridable Property Aktivitet_Table As Aktivitet_Table

End Class
